volumes:
  berry_locator_postgres_data: { }

services:
  django:
    image: berry_locator_django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start
    depends_on:
      - postgres
      - mailhog
  postgres:
    image: berry_locator_postgres
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - berry_locator_postgres_data:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"