# Generated by Django 4.2.7 on 2024-01-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='status',
        ),
    ]
