# Generated by Django 4.2.7 on 2024-01-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                (
                    'device',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to='device.devicemodel'
                    ),
                ),
            ],
        ),
    ]
