# Generated by Django 4.2.7 on 2024-01-29 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmodel',
            name='status',
            field=models.TextField(default='DISCONNECTED'),
            preserve_default=False,
        ),
    ]
