# Generated by Django 4.2.4 on 2023-11-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(max_length=255)),
                ('bind_timestamp', models.DateTimeField()),
                ('unbind_timestamp', models.DateTimeField()),
                ('status', models.TextField()),
            ],
        ),
    ]
