# Generated by Django 4.2.7 on 2023-12-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BerryDjangoSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='unbind_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
