# Generated by Django 4.2.7 on 2024-01-13 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BerryDjangoSite', '0002_usermodel_alter_devicemodel_unbind_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BerryDjangoSite.devicemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BerryDjangoSite.usermodel')),
            ],
        ),
    ]
