# Generated by Django 4.2.7 on 2024-01-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BerryDjangoSite', '0003_assignmentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='status',
        ),
        migrations.AddField(
            model_name='assignmentmodel',
            name='status',
            field=models.TextField(default='CONNECTED'),
            preserve_default=False,
        ),
    ]
